### ISSUE TITLE
环境配置失败，请问有复现出来的么

### ISSUE THREAD

**Issue by emotionee** [httle/ARS-DETR#10]

**Comment by dwddw** [comment]
试试
torch==1.11.0+cu113
mmcv-full==1.7.0
mmdet==2.28.2
mmengine==0.10.1
mmrotate==0.3.4

**Comment by floatingstarZ** [comment]
基本可以复现，结果和论文是一致的

**Comment by lsjEric** [comment]
> 基本可以复现，结果和论文是一致的
请问一下你复现的环境是什么

**Comment by floatingstarZ** [comment]
> > 基本可以复现，结果和论文是一致的
> > 请问一下你复现的环境是什么

2024-03-25 12:45:58,958 - mmrotate - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) [GCC 11.4.0]
CUDA available: True
GPU 0,1: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
PyTorch: 1.12.1+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu102
OpenCV: 4.9.0
MMCV: 1.7.1
MMCV Compiler: GCC 5.5
MMCV CUDA Compiler: 10.1
MMRotate: 0.1.0+

**Comment by floatingstarZ** [comment]
> > 基本可以复现，结果和论文是一致的
> > 请问一下你复现的环境是什么
2024-03-25 12:45:58,958 - mmrotate - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) [GCC 11.4.0]
CUDA available: True
GPU 0,1: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
PyTorch: 1.12.1+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu102
OpenCV: 4.9.0
MMCV: 1.7.1
MMCV Compiler: GCC 5.5
MMCV CUDA Compiler: 10.1
MMRotate: 0.1.0+          
不用严格要求一致，差不多就可以复现

**Comment by lsjEric** [comment]
> > > 基本可以复现，结果和论文是一致的
> > > 请问一下你复现的环境是什么
> > > 2024-03-25 12:45:58,958 - mmrotate - INFO - Environment info:
> 
> sys.platform: linux Python: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) [GCC 11.4.0] CUDA available: True GPU 0,1: GeForce RTX 2080 Ti CUDA_HOME: /usr/local/cuda NVCC: Cuda compilation tools, release 10.1, V10.1.24 GCC: gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010 PyTorch: 1.12.1+cu102 PyTorch compiling details: PyTorch built with:
> 
> * GCC 7.3
> * C++ Version: 201402
> * Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * LAPACK is enabled (usually provided by MKL)
> * NNPACK is enabled
> * CPU capability usage: AVX2
> * CUDA Runtime 10.2
> * NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
> * CuDNN 7.6.5
> * Magma 2.5.2
> * Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
> 
> TorchVision: 0.13.1+cu102 OpenCV: 4.9.0 MMCV: 1.7.1 MMCV Compiler: GCC 5.5 MMCV CUDA Compiler: 10.1 MMRotate: 0.1.0+ 不用严格要求一致，差不多就可以复现

当我安装了mmcv-full==1.7.1 mmrotate==0.1.0 运行时提示AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=1.4.5, <=1.5.0.

**Comment by floatingstarZ** [comment]
mmrotate/__init__.py里的版本改一下就行

**Comment by lsjEric** [comment]
> mmrotate/**init**.py里的版本改一下就行

非常感谢我已经装完了，请问您在训练时最高的mAP值达到了多少

**Comment by floatingstarZ** [comment]
DIOR-R：65.7，DOTA-v1.0（测试集）：72.9

**Comment by RSer-XDU** [comment]
@floatingstarZ  我想请问一下您能展示一下在DIOR数据集上各个类别的检测结果吗？我跑出来的结果每个类别虚警都特别高。你如果没有遇到这个问题，可以展示一下您的config吗？感谢
![微信图片_20240622103328](https://github.com/httle/ARS-DETR/assets/87374716/1372c1c2-e1d4-4c2f-a69d-b72fb10c3d21)

**Comment by floatingstarZ** [comment]
Dets多是因为没有选取Scores阈值进行检测框筛选，有大量的低置信度冗余框，但不太影响指标，可视化的时候直接去掉就行。我跑出来的DIOR各个类结果：
![image](https://github.com/httle/ARS-DETR/assets/35644942/d0c54aa5-7da2-4349-a206-291871d0052e)

**Comment by lsjEric** [comment]
> DIOR-R：65.7，DOTA-v1.0（测试集）：72.9
请问您在推理test数据集的时候有没有遇到全是错位的情况，我推理出来的图片几乎全是错位，验证集就是正常的，想要请教一下

**Comment by lsj1111** [comment]
> DIOR-R：65.7，DOTA-v1.0（测试集）：72.9
请问能分享一下训练的配置吗，我照着作者的这个似乎配置似乎无法复现

**Comment by lsj1111** [comment]
> DIOR-R：65.7，DOTA-v1.0（测试集）：72.9

@floatingstarZ 我按照论文的配置尝试了很多次都没达到72.9这个值，因为label没有真值能供我在训练时通过mAP值进行调参，所以我很想知道您的lr等参数是如何设置的，希望您能指导一下，非常感谢。

**Comment by floatingstarZ** [comment]
***@***.***



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月16日 18:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [httle/ARS-DETR] 环境配置失败，请问有复现出来的么 (Issue #10) |

DIOR-R：65.7，DOTA-v1.0（测试集）：72.9

@floatingstarZ 我按照论文的配置尝试了很多次都没达到72.9这个值，因为label没有真值能供我在训练时通过mAP值进行调参，所以我很想知道您的lr等参数是如何设置的，希望您能指导一下，非常感谢。

**Comment by floatingstarZ** [comment]
邮件联系吧：ziyuehuang@buaa.edu.cn

**Comment by heheda216** [comment]
2024-11-26 23:27:44,882 - mmrotate - INFO - workflow: [('train', 1)], max: 36 epochs
2024-11-26 23:27:44,882 - mmrotate - INFO - Checkpoints will be saved to /sda3.7T/hhttgp/zhouzefan/detr/ARS-DETR-ars/output by HardDiskBackend.
Traceback (most recent call last):
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS-DETR-ars/tools/train.py", line 182, in <module>
    main()
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS-DETR-ars/tools/train.py", line 171, in main
    train_detector(
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS-DETR-ars/mmrotate/apis/train.py", line 156, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1085, in __init__
    self._reset(loader, first_iter=True)
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1118, in _reset
    self._try_put_index()
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1352, in _try_put_index
    index = self._next_index()
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 624, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/sda3.7T/hhttgp/zhouzefan/detr/ARS/lib/python3.10/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

我在训练时遇到了这个错误，请您能指导一下吗
